# SonarCloud – substitua pelos valores do seu projeto (Project Settings → General Settings)
sonar.organization=walternascimentobarroso_cv-parse
sonar.projectKey=walternascimentobarroso

sonar.sources=src
sonar.python.version=3.12
