sonar.organization=walternascimentobarroso
sonar.projectKey=walternascimentobarroso_cv-parse

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
